runtime:
  cache_dir: ./.cache/antora
site:
  title: Meta Site
  url: https://metasite.netlify.com
  start_page: integreatly::index
content:
  sources:
  - url: https://github.com/finp/tutorial-web-app.git
    branches: stacey-review
    start_path: docs
  - url: https://github.com/finp/rhmap-docs.git
    branches: master
    start_path: docs
  - url: https://github.com/aerogear/mobile-docs.git
    branches: master
  - url: https://github.com/aerogear/mobile-security.git
    branches: master
ui:
  bundle:
    url: https://github.com/finp/rh-ui/raw/master/build/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
  - ./lib/remote-include-processor

  attributes:
    context: 'antora'
    location: 'remote'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
