// include::shared/attributes.adoc[]

[[account]]
= Account

.Overview
The Account Settings Section has a number of functions. Users can view account overview information such as the account type, and associated email. Users can also manage their account password settings from here. API and SSH Keys can also be managed from the Account section.

.Requirements
There are no special requirements to be able to view user account information.

.Related Resources
* https://www.npmjs.com/package/fh-fhc[FHC CLI^]
* link:{PlatformAPI}#api-keys-api[Platform API - API Keys]

[[manage-account]]
== Manage Account

This section of the Account area shows your account details such as Name, e-mail address and your account type. Account Preferences, such as re-enabling the Welcome introduction or always showing the context help, can be modified here. Your password can be changed on this page too.

[[ssh-key-management]]
== SSH Key Management

Accessing your App repos via Git requires you to upload an SSH Public key. This section of the Account area helps you do just that. You can upload multiple keys if you have a different key on various machines, or want to allow someone access. Keys can also be searched, based on the label you gave it, or deleted.

Your SSH key is typically located in:

....
~/.ssh/id_rsa.pub
....

Or, to generate a new key use:

....
ssh-keygen -t rsa -C "your_email@example.com"
....

WARNING: Any SSH key added here will have push & pull access to the Git repositories of every Project/App you can see in the Projects tab.

WARNING: An SSH key can only be uploaded once. If you attempt to uploaded an already existing key, even in someone else's account, it will fail. This behaviour is essential for mapping keys to a Users account.

[[api-key-management]]
== API key Management

In a traditional web application the user authenticates with the server, and then a cookie is incorporated into all subsequent requests sent to that user. RHMAP replaces the traditional method and uses an API key which is similar to a cookie but is sent in a header called `X-FH-AUTH-USER`. This header must be incorporated into every request sent to the user.

User API keys can be viewed in the *My Account* -> *My Profile* -> *API Keys* section of the App Studio. In the *API Keys* section of the App Studio, users can create, list, edit and revoke their user API keys. When accessing the REST API programmatically, a valid user API key must be manually set in the "X-FH-AUTH-USER" header field for each request.

By default, you will have no User API keys (with the exception of any system created keys for example, `FH_MBAAS_API_key`). Multiple API keys can be created, so its a good idea to give each a unique label. The key value will be generated automatically. Labels can be modified later if required. If you no longer require a specific key or wish to prevent it from being used any more (for security reasons), simple Delete/Revoke it.
