// include::shared/attributes.adoc[]

[[app-credentials-bundles]]
= App Credentials Bundles

A Credentials Bundle consists of a number of resources needed to perform a particular build. Here, the different resources are listed, along with a brief explanation of their purpose.

[[resources]]
== Resources

When performing build operations, a Credentials bundle can sometimes be required (depending on the build). A Credential bundle is a combination of resources, such as certificates, provisioning profiles, and private keys, necessary for performing specific types of builds, be it a development build, distribution build, debug build etc. Depending on both the platform, and the build type, different resources will be grouped together to constitute a bundle.

Listed below is a breakdown of resources that can be added to a Credentials Bundle, along with a brief description of what they are used for.

[[all-platforms]]
=== All Platforms

* Private Key
** This is a file whose contents are known only to the owner. During the app building process, the app is digitally signed using this key. This means the developers digital signature is left on the App, allowing the App to be tied back to the developer.

[[android-only]]
=== Android Only

* Android Distribution Certificate - Used to build Apps for upload to the Google Play Store. This certificate is used to identify you as the developer upon upload to the market.
* Signing key

. Use `keytool` to create a signing key:
+
[source,bash]
----
keytool -genkey -v -keystore redhat.keystore -alias rhmap -keyalg RSA -keysize 2048 -validity 10000
----
+
. Export the java keystore key intp pkcs#12 format:
+
[source,bash]
----
keytool -importkeystore -srckeystore redhat.keystore -destkeystore rhmap.p12 -deststoretype PKCS12 -srcalias rhmap
----
+
. Extract the Distribution Certificate:
+
[source,bash]
----
openssl pkcs12 -in rhmap.p12 -nokeys -out rhmap-cert.pem
----
+
. Extract the Private Key
+
[source,bash]
----
openssl pkcs12 -in rhmap.p12 -nodes -nocerts -out rhmap-key.pem
----
+
where:
+
** Private Key is `rhmap-key.pem`
** Certificate is `rhmap-cert.pem`



[[ios-only]]
=== iOS Only

* iOS Development Certificate
** Used to run an iOS App on devices during development.
* iOS Distribution Certificate
** Used for submitting your iOS App to the App Store, and for distributing the App for On-Device testing. This is also used to identify you as the developer.
+
[WARNING]
If you use an enterprise distribution certificate to sign a Swift-based iOS app built using the Build Farm, the resulting app may crash upon startup.
If you encounter this problem, refer to the Red Hat Knowledge Base article link:https://access.redhat.com/solutions/2292651[Swift-based iOS application crashes upon startup when signed using an enterprise distribution certificate without Organisational Unit field^] for detailed instructions on how to resolve the problem.

* Provisioning Profile
** Necessary in order to install development applications on iOS devices.

[[apple-developer-and-enterprise-accounts]]
== Apple Developer and Enterprise Accounts

In order to publish an app in the Apple App Store you must have an active apple account (developer or enterprise). This account will need to be renewed annually in order for associated apps to continue to be available in the App Store.

[[developer-account]]
=== Developer Account

A developer account is used create an iOS distribution certificates used to publish apps to the apple App Store.

When a distribution certificate expires, if the iOS Developer account is still active, existing apps on the App Store will not be affected, they will continue be available within the App Store and apps already on device will continue to function as expected.

[[enterprise-account]]
=== Enterprise Account

An enterprise account is used to create (in-house) distribution certificates which are needed to publish apps to the {ProductShortName} app store or customer in-house MDM.

When an existing in-house certificate expires all apps built with that certificate will not run and further installs of this version of the app will not be possible.

The app will need to be rebuilt, signed with a new certificate, republished to the relevant store and then re-downloaded by all users.

[[ios-certificate-renewal]]
=== iOS Certificate Renewal

Apple enterprise and developer certificates must be recreated every three years.

The customer email address associated with the developer account will receive advance notification of the impending renewal requirement.

While Red Hat might have been involved in assisting a customer with the initial setup of an Apple developer or enterprise account the ownership and responsibility for the apple account and the certificates created remains with the customer.

Upon receiving the certificate expiry notification it is recommended that the customer proactively renew the certificate in order to avoid interruption to their apps availability.
